
class XLConfig:
    ADDRESS_LED            = 7
    ADDRESS_OPERATING_MODE = 11
    ADDRESS_VELOCITY_LIMIT = 44
    ADDRESS_TORQUE_ENABLE  = 64
    ADDRESS_LED            = 65
    ADDRESS_GOAL_VELOCITY  = 104

    OPERATING_MODE_VELOCITY_CONTROL_MODE = 1
    OPERATING_MODE_POSITION_CONTROL_MODE = 3

